api_platform:
  mapping:
    paths: ['%kernel.project_dir%/config/api_platform', '%kernel.project_dir%/src/ApiResource']
  formats:
    json: ['application/json']
    jsonld: ['application/json+ld']
    html: ['text/html']
    multipart: ['multipart/form-data']
  patch_formats:
    json: [ 'application/merge-patch+json' ]
  swagger:
    versions: [3]
    api_keys:
      apiKey:
        name: Authorization
        type: header
  path_segment_name_generator: api_platform.path_segment_name_generator.dash
  defaults:
    pagination_partial: false
    pagination_items_per_page: 10
    pagination_client_items_per_page: true
    pagination_maximum_items_per_page: 100
  collection:
    pagination:
      items_per_page_parameter_name: 'itemsPerPage'