framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        default_bus: command.bus

        buses:
            command.bus: ~
            event.bus: ~

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            # Route messages to the transports
            'App\Message\Event\Assignment\AssignmentCreatedEvent': async
            'App\Message\Event\Assignment\AssignmentGradedEvent': async
            'App\Message\Event\Assignment\AssignmentUpdatedEvent': async
            'App\Message\Event\Functionality\FunctionalityCreatedEvent': async
            'App\Message\Event\GuidanceMeeting\GuidanceMeetingCreatedEvent': async
            'App\Message\Event\GuidanceMeeting\GuidanceMeetingCanceledEvent': async
            'App\Message\Event\GuidanceMeeting\GuidanceMeetingMissedEvent': async
            'App\Message\Event\GuidanceMeeting\GuidanceMeetingUpdatedEvent': async
            'App\Message\Event\MilestoneMeeting\MilestoneMeetingCreatedEvent': async
            'App\Message\Event\MilestoneMeeting\MilestoneMeetingCanceledEvent': async
            'App\Message\Event\MilestoneMeeting\MilestoneMeetingMissedEvent': async
            'App\Message\Event\MilestoneMeeting\MilestoneMeetingUpdatedEvent': async
            'App\Message\Event\MilestoneMeeting\MilestoneMeetingGradedEvent': async

            'App\Message\Command\Assignment\CreateAssignmentCommand': sync
            'App\Message\Command\Assignment\UpdateAssignmentCommand': sync
            'App\Message\Command\Functionality\CreateFunctionalityCommand': sync
            'App\Message\Command\GuidanceMeeting\CreateGuidanceMeetingCommand': sync
            'App\Message\Command\GuidanceMeeting\UpdateGuidanceMeetingCommand': sync
            'App\Message\Command\MilestoneMeeting\CreateMilestoneMeetingCommand': sync
            'App\Message\Command\MilestoneMeeting\UpdateMilestoneMeetingCommand': sync


# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
