vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    student_import_file:
      uri_prefix: /documents/students
      upload_destination: '%kernel.project_dir%/public/documents/students'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\OrignameNamer
    supervisor_import_file:
      uri_prefix: /documents/supervisors
      upload_destination: '%kernel.project_dir%/public/documents/supervisors'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\OrignameNamer
    assignment_document_upload:
      uri_prefix: /documents/assignments
      upload_destination: '%kernel.project_dir%/public/documents/assignments'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\OrignameNamer
#      directory_namer:
#        service: vich_uploader.namer_directory_property
#        options: { property: 'assignmentId', transliterate: true }
      delete_on_remove: true
    functionality_attachment_upload:
      uri_prefix: /documents/functionalities
      upload_destination: '%kernel.project_dir%/public/documents/functionalities'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\OrignameNamer
      delete_on_remove: true