vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    student_import_file:
      uri_prefix: /documents/students
      upload_destination: '%kernel.project_dir%/public/documents/students'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\OrignameNamer
    supervisor_import_file:
      uri_prefix: /documents/supervisors
      upload_destination: '%kernel.project_dir%/public/documents/supervisors'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\OrignameNamer