App\Entity\Document:
  normalizationContext:
    groups: [ 'assignment_document_upload:output' ],
  types: [ 'https://schema.org/MediaObject' ]
  operations:
    ApiPlatform\Metadata\Post:
      security: 'is_granted("ROLE_STUDENT")'
      processor: App\State\Processor\DocumentStateProcessor
      validationContext:
        groups: [ 'Default', 'assignment_document_upload:input' ] ]
      openapiContext:
        requestBody:
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  file:
                    type: string
                    format: binary
                  assignmentId:
                    type: string
    ApiPlatform\Metadata\Delete:
      provider: App\State\Provider\Assignment\GetDocumentItemProvider