App\Entity\FunctionalityAttachment:
  normalizationContext:
    groups: [ 'functionality_attachment_upload:output' ],
  types: [ 'https://schema.org/MediaObject' ]
  operations:
    ApiPlatform\Metadata\Post:
      security: 'is_granted("ROLE_STUDENT")||is_granted("ROLE_TEACHER")'
      processor: App\State\Processor\FunctionalityAttachmentStateProcessor
      validationContext:
        groups: [ 'Default', 'functionality_attachment_upload:input' ] ]
      openapiContext:
        requestBody:
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  file:
                    type: string
                    format: binary
                  functionalityId:
                    type: string
    ApiPlatform\Metadata\Delete: ~