App\Entity\Functionality:
  operations:
    ApiPlatform\Metadata\Get:
      security: 'is_granted("ROLE_STUDENT")||is_granted("ROLE_TEACHER")'
      provider: App\State\Provider\Functionality\GetFunctionalityItemProvider
      output: App\Dto\Functionality\Output\FunctionalityOutputDto
    ApiPlatform\Metadata\GetCollection:
      security: 'is_granted("ROLE_STUDENT")||is_granted("ROLE_TEACHER")'
      filters: [ 'functionality.search_filter', 'functionality.date_filter', 'functionality.order_filter' ]
      provider: App\State\Provider\Functionality\GetFunctionalityCollectionProvider
      output: App\Dto\Functionality\Output\FunctionalityOutputDto
    ApiPlatform\Metadata\Post:
      securityPostDenormalize: 'is_granted("FUNCTIONALITY_CREATE", object)'
      input: App\Dto\Functionality\Input\CreateFunctionalityInputDto
      processor: App\State\Processor\Functionality\CreateFunctionalityProcessor
      output: App\Dto\Functionality\Output\FunctionalityOutputDto
    ApiPlatform\Metadata\Delete:
      security: 'is_granted("FUNCTIONALITY_DELETE", object)'
      processor: App\State\Processor\Functionality\DeleteFunctionalityStateProcessor
    ApiPlatform\Metadata\Patch:
      security: 'is_granted("FUNCTIONALITY_EDIT", object)'
      input: App\Dto\Functionality\Input\PatchFunctionalityInputDto
      output: App\Dto\Functionality\Output\FunctionalityOutputDto
      provider: App\State\Provider\Functionality\PatchFunctionalityProvider
      processor: App\State\Processor\Functionality\PatchFunctionalityStateProcessor