App\Entity\FunctionalityAttachment:
  types: [ 'https://schema.org/MediaObject' ]
  operations:
    APiPlatform\Metadata\GetCollection:
      filters: [ 'functionality_attachments.search_filter' ]
      output: App\Dto\Document\Output\DocumentOutputDto
      provider: App\State\Provider\Functionality\GetAttachmentCollectionProvider
    ApiPlatform\Metadata\Post:
      normalizationContext:
        groups: [ 'functionality_attachment_upload:output' ],
      security: 'is_granted("ROLE_STUDENT")||is_granted("ROLE_TEACHER")'
      processor: App\State\Processor\FunctionalityAttachmentStateProcessor
      validationContext:
        groups: [ 'Default', 'functionality_attachment_upload:input' ] ]
      openapiContext:
        requestBody:
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  file:
                    type: string
                    format: binary
                  functionalityId:
                    type: string
    ApiPlatform\Metadata\Delete:
      provider: App\State\Provider\Functionality\GetAttachmentItemProvider