App\Entity\FunctionalityType:
  operations:
    ApiPlatform\Metadata\Get:
#      security: 'is_granted("ROLE_USER")'
      output: App\Dto\Functionality\Output\TypeOutputDto
      provider: App\State\Provider\Functionality\GetTypeItemProvider
    ApiPlatform\Metadata\GetCollection:
#      security: 'is_granted("ROLE_USER")'
      output: App\Dto\Functionality\Output\TypeOutputDto
      provider: App\State\Provider\Functionality\GetTypeCollectionProvider