App\Entity\FunctionalityStatus:
  normalizationContext:
    groups: [ 'status:output' ]
  operations:
    ApiPlatform\Metadata\Get:
      security: 'is_granted("ROLE_USER")'
    ApiPlatform\Metadata\GetCollection:
      security: 'is_granted("ROLE_USER")'
