App\Entity\GuidanceMeeting:
  operations:
    ApiPlatform\Metadata\Get:
      provider: App\State\Provider\GuidanceMeeting\GetGuidanceMeetingItemProvider
      output: App\Dto\Meeting\Output\GuidanceMeetingOutputDto
    ApiPlatform\Metadata\GetCollection:
      filters: [ 'guidance_meeting.search_filter', 'guidance_meeting.date_filter' ]
      provider: App\State\Provider\GuidanceMeeting\GetGuidanceMeetingsCollectionProvider
      output: App\Dto\Meeting\Output\GuidanceMeetingOutputDto
    ApiPlatform\Metadata\Post:
      input: App\Dto\Meeting\Input\CreateMeetingInputDto
      processor: App\State\Processor\CreateGuidanceMeetingStateProcessor
      output: App\Dto\Meeting\Output\GuidanceMeetingOutputDto
    ApiPlatform\Metadata\Patch:
      input: App\Dto\Meeting\Input\PatchGuidanceMeetingInputDto
      output: App\Dto\Meeting\Output\GuidanceMeetingOutputDto
      provider: App\State\Provider\GuidanceMeeting\PatchGuidanceMeetingItemProvider
      processor: App\State\Processor\PatchGuidanceMeetingStateProcessor
    ApiPlatform\Metadata\Delete: ~