App\Entity\Project:
  operations:
    ApiPlatform\Metadata\Get:
      output: App\Dto\Project\Output\ProjectInformationOutputDto
      security: 'is_granted("ROLE_USER")'
      provider: App\State\Provider\GetProjectInformationProvider
    ApiPlatform\Metadata\GetCollection:
      filters: ['project.search_filter']
      security: 'is_granted("ROLE_USER")'
    ApiPlatform\Metadata\Patch:
      input: App\Dto\Project\Input\PatchProjectInputDto
      security: 'is_granted("PROJECT_EDIT", object)'
      provider: App\State\Provider\PatchProjectItemProvider
      processor: App\State\Processor\PatchProjectProcessor