App\Entity\FunctionalityAttachment:
  attributes:
    contentUrl:
      types: ['https://schema.org/contentUrl']
      groups: ['functionality_attachment_upload:output']
    file:
      groups: ['functionality_attachment_upload:input']
    createdAt:
      groups: [ 'functionality_attachment_upload:input' ]