App\Entity\FunctionalityStatus:
  attributes:
    id:
      groups: [ 'status:output', 'status_history:output' ]
    name:
      groups: [ 'status:output', 'status_history:output' ]
    orderNumber:
      groups: [ 'status:output', 'status_history:output' ]