App\Entity\Student:
  attributes:
    firstName:
      groups: [ 'student:input', 'student:output' ]
    lastName:
      groups: [ 'student:input', 'student:output' ]
    phoneNumber:
      groups: [ 'student:input', 'student:output']