App\ApiResource\User:
  attributes:
    code:
      identifier: true
      groups: [ 'user:output' ]
    email:
      groups: [ 'user:output' ]
#    plainPassword:
#      groups: [ 'user:create' ]
#      serialized_name: 'password'
    firstName:
      groups: [ 'user:output' ]
    lastName:
      groups: [ 'user:output' ]
    roles:
      groups: [ 'user:output' ]