App\ApiResource\User:
  attributes:
    code:
      identifier: true
      groups: [ 'user:create', 'user:output' ]
#      identifier: true
#    id:
#      identifier: false
    email:
      groups: [ 'user:create', 'user:output' ]
    plainPassword:
      groups: [ 'user:create' ]
      serialized_name: 'password'
    firstName:
      groups: [ 'user:create', 'user:output' ]
    lastName:
      groups: [ 'user:create', 'user:output' ]
    roles:
      groups: [ 'user:output' ]
    discriminator:
      groups: [ 'user:output' ]
    isStudent:
      groups: ['user:create']