# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.admin_email_address: '%env(APP_ADMIN_EMAIL_ADDRESS)%'
    app.admin_password: '%env(APP_ADMIN_PASSWORD)%'
    app.admin_code: '%env(APP_ADMIN_CODE)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\OpenApi\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@.inner' ]

    # fixtures
    App\DataFixtures\AdminAccountFixture:
        bind:
            $adminEmail: '%app.admin_email_address%'
            $adminPassword: '%app.admin_password%'
            $adminCode: '%app.admin_code%'

    # event listeners
    acme_api.event.jwt_created_listener:
        class: App\EventListener\JWTCreatedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    # filters
    score_weight.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: 'exact'} ]
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false

    student.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { project.supervisor.user.code: 'exact' } ]
        tags: [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines (by adding them in the defaults section)
        autowire: false
        autoconfigure: false
        public: false

    milestone_meeting.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { project.id: 'exact', isCompleted: 'exact', isCanceled: 'exact' } ]
        tags: [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines (by adding them in the defaults section)
        autowire: false
        autoconfigure: false
        public: false

    milestone_meeting.date_filter:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [ { scheduledAt: ~ } ]
        tags: [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines (by adding them in the defaults section)
        autowire: false
        autoconfigure: false
        public: false

    guidance_meeting.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { project.id: 'exact', isCompleted: 'exact', isCanceled: 'exact' } ]
        tags: [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines (by adding them in the defaults section)
        autowire: false
        autoconfigure: false
        public: false

    guidance_meeting.date_filter:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [ { scheduledAt: ~ } ]
        tags: [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines (by adding them in the defaults section)
        autowire: false
        autoconfigure: false
        public: false

    assignment.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { project.id: 'exact' } ]
        tags: [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines (by adding them in the defaults section)
        autowire: false
        autoconfigure: false
        public: false

    assignment.date_filter:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [ { dueDate: ~ } ]
        tags: [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines (by adding them in the defaults section)
        autowire: false
        autoconfigure: false
        public: false

    setting.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: 'exact' } ]
        tags: [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines (by adding them in the defaults section)
        autowire: false
        autoconfigure: false
        public: false

    functionality.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { title: 'partial', project.id: 'exact', type.id: 'exact', functionalityStatus.id: 'exact', parentFunctionality.id: 'exact' } ]
        tags: [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines (by adding them in the defaults section)
        autowire: false
        autoconfigure: false
        public: false

    functionality.date_filter:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [ { dueDate: ~, createdAt: ~ } ]
        tags: [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines (by adding them in the defaults section)
        autowire: false
        autoconfigure: false
        public: false

    functionality.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments:
            $properties: { orderNumber: ~}
            $orderParameterName: order
        tags: [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines (by adding them in the defaults section)
        autowire: false
        autoconfigure: false
        public: false

    project.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { supervisor.user.id: 'exact', student.user.id: 'exact' } ]
        tags: [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines (by adding them in the defaults section)
        autowire: false
        autoconfigure: false
        public: false

    history.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { project.id: 'exact', status.id: 'exact' } ]
        tags: [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines (by adding them in the defaults section)
        autowire: false
        autoconfigure: false
        public: false

    history.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments:
            $properties: { id: ~ }
            $orderParameterName: order
        tags: [ 'api_platform.filter' ]
        # The following are mandatory only if a _defaults section is defined with inverted values.
        # You may want to isolate filters in a dedicated file to avoid adding the following lines (by adding them in the defaults section)
        autowire: false
        autoconfigure: false
        public: false

    # processors
    App\State\Processor\UserStateProcessor:
        bind:
            $decorated: '@api_platform.doctrine.orm.state.persist_processor'

    App\State\Processor\StudentImportFileStateProcessor:
        bind:
            $decorated: '@api_platform.doctrine.orm.state.persist_processor'

    App\State\Processor\SupervisorImportFileStateProcessor:
        bind:
            $decorated: '@api_platform.doctrine.orm.state.persist_processor'

    App\State\Processor\ProjectSupervisoryPlanProcessor: ~
#    App\State\Processor\CreateMilestoneMeetingStateProcessor: ~
#    App\State\Processor\CreateGuidanceMeetingStateProcessor: ~
#        bind:
#            $requestContext: '@request_stack'

    App\State\Processor\Assignment\DeleteAssignmentStateProcessor:
        bind:
            $decoratedProcessor: '@api_platform.doctrine.orm.state.remove_processor'

    App\State\Processor\DocumentStateProcessor:
        bind:
            $decorated: '@api_platform.doctrine.orm.state.persist_processor'

    App\State\Processor\FunctionalityAttachmentStateProcessor:
        bind:
            $decorated: '@api_platform.doctrine.orm.state.persist_processor'

    App\State\Processor\Functionality\DeleteFunctionalityStateProcessor:
        bind:
            $decoratedProcessor: '@api_platform.doctrine.orm.state.remove_processor'

    # providers
    App\State\Provider\StudentsStateProvider:
        bind:
            $decoratedProvider: '@api_platform.doctrine.orm.state.collection_provider'

    App\State\Provider\SupervisorsStateProvider:
        bind:
            $decoratedProvider: '@api_platform.doctrine.orm.state.collection_provider'

    App\State\Provider\PatchProjectSupervisoryPlanProvider: ~
    App\State\Provider\GetProjectSupervisoryPlanProvider: ~
    App\State\Provider\GetProjectInformationProvider: ~

    # milestone meetings
    App\State\Provider\MilestoneMeeting\MilestoneMeetingsCollectionProvider:
        bind:
            $decoratedProvider: '@api_platform.doctrine.orm.state.collection_provider'

    App\State\Provider\MilestoneMeeting\GetMilestoneMeetingItemProvider:
        bind:
            $decoratedProvider: '@api_platform.doctrine.orm.state.item_provider'

    App\State\Provider\MilestoneMeeting\PatchMilestoneMeetingItemProvider: ~

    # guidance meetings
    App\State\Provider\GuidanceMeeting\PatchGuidanceMeetingItemProvider: ~

    App\State\Provider\GuidanceMeeting\GetGuidanceMeetingsCollectionProvider:
        bind:
            $decoratedProvider: '@api_platform.doctrine.orm.state.collection_provider'

    App\State\Provider\GuidanceMeeting\GetGuidanceMeetingItemProvider:
        bind:
            $decoratedProvider: '@api_platform.doctrine.orm.state.item_provider'

    # assignments
    App\State\Provider\Assignment\GetAssignmentCollectionProvider:
        bind:
            $decoratedProvider: '@api_platform.doctrine.orm.state.collection_provider'

    App\State\Provider\Assignment\GetAssignmentItemProvider:
        bind:
            $decoratedProvider: '@api_platform.doctrine.orm.state.item_provider'

    # functionalities
    App\State\Provider\Functionality\GetFunctionalityCollectionProvider:
        bind:
            $decoratedProvider: '@api_platform.doctrine.orm.state.collection_provider'

    App\State\Provider\Functionality\GetFunctionalityItemProvider:
        bind:
            $decoratedProvider: '@api_platform.doctrine.orm.state.item_provider'

    App\State\Provider\Functionality\GetTypeCollectionProvider:
        bind:
            $decoratedProvider: '@api_platform.doctrine.orm.state.collection_provider'

    App\State\Provider\Functionality\GetTypeItemProvider:
        bind:
            $decoratedProvider: '@api_platform.doctrine.orm.state.item_provider'

    # services
    App\Service\ScoreWeightsService: ~
    App\Service\Contract\ScoreWeightsServiceInterface: '@App\Service\ScoreWeightsService'

    App\Validator\PatchMeetingValidator: ~
    App\Validator\Contracts\ValidatorInterface $meetingValidator: '@App\Validator\PatchMeetingValidator'

    App\Validator\RatingValidator: ~
    App\Validator\Contracts\ValidatorInterface $ratingValidator: '@App\Validator\RatingValidator'

    App\Validator\FunctionalityValidator: ~
    App\Validator\Contracts\ValidatorInterface $functionalityValidator: '@App\Validator\FunctionalityValidator'
