resources:
  App\Entity\User:
    processor: App\State\UserStateProcessor
    shortName: 'Users'
    normalizationContext:
      groups: [ 'user:output' ]
#    collectionOperations:
#      post:
#        path: '/register'
#        openapi_context:
#          summary: 'Create an account'
#          description: 'Create an account'
#    itemOperations:
#      get: ~
    operations:
      ApiPlatform\Metadata\Get:
        provider: App\State\Provider\UserStateProvider
        uriTemplate: '/users/{code}'
      ApiPlatform\Metadata\Post:
        uriTemplate: '/register'
        openapiContext:
          summary: 'Create an account'
          description: 'Create an account'
        denormalizationContext:
          groups: [ 'user:create' ]