resources:
  App\ApiResource\User:
    shortName: 'Users'
    normalizationContext:
      groups: [ 'user:output' ]
#    collectionOperations:
#      post:
#        path: '/register'
#        openapi_context:
#          summary: 'Create an account'
#          description: 'Create an account'
#    itemOperations:
#      get: ~
    operations:
      ApiPlatform\Metadata\Get:
        provider: App\State\Provider\UserStateProvider
#        output: App\Dto\User\Output\UserOutputDto
        uriTemplate: '/users/{code}'
      ApiPlatform\Metadata\Post:
        processor: App\State\Processor\UserStateProcessor
        uriTemplate: '/register'
        openapiContext:
          summary: 'Create an account'
          description: 'Create an account'
        denormalizationContext:
          groups: [ 'user:create' ]

  App\Entity\Student:
    shortName: 'Students'
    normalizationContext:
      groups: ['student:output']
    denormalizationContext:
      groups: ['student:input']

  App\Entity\Supervisor:
    shortName: 'Supervisors'
    normalizationContext:
      groups: [ 'supervisor:output' ]
    denormalizationContext:
      groups: [ 'supervisor:input' ]